# fly.toml app configuration file generated for red-silence-64 on 2023-09-04T12:48:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "red-silence-64"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
